spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: nopassword

